#! /bin/bash

# read -p 'Please enter your username: ' username
read -p 'Please enter target folder name: ' folder

DIR="/Users/$USER/Desktop/$folder"
SUB="Submission attachment(s)"
FED="Feedback Attachment(s)"

# create an empty array to hold students who submit nothing
declare -a empty

cd ${DIR}

for item in *; do
  if [ -d "$item" ]; then
    # need to deal with .DS_STORE!q
    if [ "$(ls -A "$item"/"$SUB" | wc -l)" -ge 1 ]; then
      # or
      # [ $(ls -A "$item"/"$SUB") == ".DS_Store"]
      
      echo "Deleting student" "$item" "'s submission contents ..."
      rm -rf "$item"/"$SUB"/*
      #echo "$item"/"$SUB" "is not empty."
    else
      # the brackets are necessary 
      # otherwise all names will join into one single element
      empty+=("$item")
    fi
  else
    printf '%s %s \e[1;31m%s\e[0m %s\n' "$item" 'is' 'NOT' 'a directory.'
  fi
done
cd $HOME/Desktop

echo "Deleting DONE!"
echo
echo "Start Compressing ..."

zip -rq -9 "${folder}.zip" $folder

# delete all .DS_Store and __MACOSX
# first delete .DS_Store
if [[ $(unzip -l "${folder}.zip" | grep ".DS_Store" | wc -l) -ge 1 ]]; then 
  zip -dq "${folder}.zip" "*.DS_Store"
# then delete __MACOSX
elif [[ $(unzip -l "${folder}.zip" | grep "__MACOSX" | wc -l) -ge 1 ]]; then
  zip -dq "${folder}.zip" "*__MACOSX*"
fi

echo "Compressing DONE!"

