#! /bin/bash

# read -p 'Please enter your username: ' username
read -p 'Please enter target folder name: ' folder

DIR="/Users/$USER/Desktop/$folder"
SUB="Submission attachment(s)"
FED="Feedback Attachment(s)"

# empty array to hold students who submit nothing
declare -a empty
# load array to hold students who submit sth
declare -a load
# total array to hold all students
declare -a total

cd ${DIR}

for item in *; do
  if [ -d "$item" ]; then
    # count as one student if item is a directory
    total+=("$item")

    # check if empty, i.e either empty or mere a .DS_Store file
    if [[ "$(ls -A "$item"/"$SUB" | wc -l)" -eq 0 \
      || "$(ls -A "$item"/"$SUB")" == ".DS_Store" ]]; then
    # if empty   
      empty+=("$item")
    # if not empty  
    else
      printf '%s \e[0;34m%s\e[0m %s\n' "Copying student" "$item" "'s submussion to feedback folder"
      cp "$item"/"$SUB"/* "$item"/"$FED"/
      load+=("$item")

      # check .zip and .rar files
      if [[ $(ls "$item"/"$FED" | grep -e '\.zip$' | wc -l) -ge 1 ]]; then
        unzip -q "$item"/"$FED"/"*.zip" -d "$item"/"$FED"
        rm -rf "$item"/"$FED"/__MACOSX
        rm "$item"/"$FED"/*.zip
      fi

      if [[ $(ls "$item"/"$FED" | grep -e '\.rar$' | wc -l) -ge 1 ]]; then
        unrar x -ad -inul -o+ "$item"/"$FED"/"*.rar" "$item"/"$FED"/
        rm "$item"/"$FED"/*.rar
      fi
    fi
  else
    echo 
    printf '%s %s \e[1;31m%s\e[0m %s\n' "$item" 'is' 'NOT' 'a directory.'
  fi
done
cd $HOME/Desktop

echo "Copying DONE!"
echo
printf '\e[1;32m%d\e[0m %s\n' ${#total[@]} "students in total."
printf '\e[1;33m%d\e[0m %s\n' ${#load[@]} "students submitted homework."
printf '\e[1;31m%d\e[0m %s\n' ${#empty[@]} "students submitted nothing."

echo
if [ ${#empty[@]} -gt 0 ]; then
  printf '%s \e[1;36m%s\e[0m %s\n' "The following students have" "NO" "submission."
  for i in "${empty[@]}"; do
    echo $i
  done
fi
