#! /bin/bash

# Copy and unzip submission' contents of each stu to feedback

# read -p 'Please enter your username: ' username
read -p 'Please enter target folder name: ' folder

DIR="/Users/$USER/Desktop/$folder"
SUB="Submission attachment(s)"
FED="Feedback Attachment(s)"

# get rid of all the annoying .DS_Store files!
rm -rf $DIR/*/*/.DS_Store $DIR/*/.DS_Store

# var total to hold all students
total=$(ls -l $DIR | grep -c -e "^d")

# load holds the num of those who sub-ed sth
load=$(find $DIR/* -mindepth 1 -maxdepth 1 \! -empty | wc -l)

bar="############################################################" # 60
# barlen=${#bar}
count=1


delivery() {
  for item in *; do
    if [ -d "$item" ]; then
      # count as one student if item is a directory
      total+=("$item")

      # check if empty
      if [[ $(ls "$item"/"$SUB" | wc -l) -eq 0 ]]; then
      # if empty, create an empty array and add stu to it at the same time   
        empty+=("$item")
      # if not empty  
      else
        cp -R "$item"/"$SUB"/* "$item"/"$FED"/
        pro=$((count*100/load))
        printf "\r[%-${load}s] %2d%%" "${bar:0:++count}" $pro
        sleep 0.1

        # check .zip and .rar files
        if [[ $(ls "$item"/"$FED" | grep -e '\.zip$' | wc -l) -ge 1 ]]; then
          unzip -q "$item"/"$FED"/"*.zip" -d "$item"/"$FED" 2> /dev/null
          rm -rf "$item"/"$FED"/__MACOSX/
          rm "$item"/"$FED"/*.zip
        fi

        if [[ $(ls "$item"/"$FED" | grep -e '\.rar$' | wc -l) -ge 1 ]]; then
          unrar x -ad -inul -o+ "$item"/"$FED"/"*.rar" "$item"/"$FED"/
          rm "$item"/"$FED"/*.rar
        fi
      fi
    else
      # if not a dir, do nothing
      continue
    fi
  done
  echo
}

# start processing
printf "\e[0;33m%s\e[0m\n" "Start Copying ..."

cd ${DIR}
delivery
cd $HOME/Desktop

printf "\e[0;32m%s\e[0m\n" "Copying DONE!"
echo

printf "\e[1;32m%d\e[0m students in total.\n" $total
printf "\e[1;33m%d\e[0m students submitted homework.\n" $load
printf "\e[1;31m%d\e[0m students submitted nothing.\n" ${#empty[@]}
echo

if [ ${#empty[@]} -gt 0 ]; then
  pat='([a-zA-Z ,]+)\(([a-z0-9]+)\)'
  for i in "${empty[@]}"; do
    [[ "$i" =~ $pat ]] 
  name+=("${BASH_REMATCH[1]}")
  netid+=("${BASH_REMATCH[2]}") 
  done
fi

printf "The following students have \e[1;36m%s\e[0m submission.\n" "NO"
printf "\e[0;34m%-10s\e[0m\t\e[0;34m%-40s\e[0m\n" "NetID" "Student Name"
for ((i = 0; i < ${#name[@]}; ++i)); do
   printf "%-10s\t%-35s\n" "${netid[i]}" "${name[i]}"
done

# delet the arrays to avoid duplicate counts
unset empty load total count name netid
