#! /bin/bash
# remove all the contents in students' feedback folder

# get the dir name from user
read -p 'Please enter target folder name: ' folder

DIR="$HOME/Desktop/$folder"
SUB="Submission attachment(s)"
FED="Feedback Attachment(s)"

# get rid of all the annoying .DS_Store files!
rm -rf $DIR/*/*/.DS_Store $DIR/*/.DS_Store

# total holds the total num of the students
total=$(ls -l $DIR | grep -c -e "^d")
# load holds the num of those who sub-ed sth
load=$(find $DIR/* -mindepth 1 -maxdepth 1 \! -empty | wc -l)

bar="############################################################" # 60
# barlen=${#bar}
count=1

remove() {
  for item in *; do
    # check if the item is a dir
    if [ -d "$item" ]; then
      # count as one student if item is a directory
      # total+=("$item")

      # check if empty, i.e nothing there (but, perhaps, .DS_Store)
      if [[ $(ls "$item"/"$SUB" | wc -l) -eq 0 ]]; then
      # ==================== old and bad ======================
      # if [[ "$(ls -A "$item"/"$SUB" | wc -l)" -eq 0 \
      #   || "$(ls -A "$item"/"$SUB")" == ".DS_Store" ]]; then
      # =======================================================
      # if empty
      # empty array to hold students who submit nothing   
        empty+=("$item")
      # if not empty  
      else
        rm -rf "$item"/"$FED"/*
        # load+=("$item")
        pro=$((count*100/load))
        printf "\r[%-${load}s] %2d%%" "${bar:0:++count}" $pro
        sleep 0.1
      fi
    else
      # if not a dir, do nothing
      continue
    fi
  done
  echo
}

# start processing
printf "\e[0;33m%s\e[0m\n" "Start Deleting ..."
cd ${DIR}
remove
cd $HOME/Desktop

printf "\e[0;32m%s\e[0m\n" "Deleting DONE!"
echo
printf "\e[1;32m%d\e[0m students in total.\n" $total
printf "\e[1;33m%d\e[0m students got feedback.\n" $load
printf "\e[1;31m%d\e[0m students submitted nothing.\n" ${#empty[@]}

echo
if [ ${#empty[@]} -gt 0 ]; then
    declare -a name
    declare -a netid
    pat='([a-zA-Z ,]+)\(([a-z0-9]+)\)'
  for i in "${empty[@]}"; do
    [[ "$i" =~ $pat ]] 
	name+=("${BASH_REMATCH[1]}")
	netid+=("${BASH_REMATCH[2]}")	
  done
fi

printf "The following students have \e[1;36m%s\e[0m submission.\n" "NO"
printf "\e[0;34m%-10s\e[0m\t\e[0;34m%-40s\e[0m\n" "NetID" "Student Name"
for ((i = 0; i < ${#name[@]}; ++i)); do
   printf "%-10s\t%-35s\n" "${netid[i]}" "${name[i]}"
done
unset empty load total count
