#! /bin/bash

# read -p 'Please enter your username: ' username
read -p 'Please enter target folder name: ' folder

DIR="$HOME/Desktop/$folder"
SUB="Submission attachment(s)"
FED="Feedback Attachment(s)"

# empty array to hold students who submit nothing
declare -a empty
# load array to hold students who submit sth
declare -a load
# total array to hold all students
declare -a total

cd ${DIR}

for item in *; do
  if [ -d "$item" ]; then
    # count as one student if item is a directory
    total+=("$item")

    # check if empty, i.e either empty or mere a .DS_Store file
    if [[ "$(ls -A "$item"/"$SUB" | wc -l)" -eq 0 \
      || "$(ls -A "$item"/"$SUB")" == ".DS_Store" ]]; then
    # if empty   
      empty+=("$item")
    # if not empty  
    else
      # printf '%s \e[0;34m%s\e[0m%s\n' "Deleting student" "$item" "'s feedback content"
      rm -rf "$item"/"$FED"/*
      load+=("$item")
    fi
  else
    # echo 
    # printf '%s %s \e[1;31m%s\e[0m %s\n' "$item" 'is' 'NOT' 'a directory.'
    continue
  fi
done
cd $HOME/Desktop

echo "Deleting DONE!"
echo
printf '\e[1;32m%d\e[0m students in total.\n' ${#total[@]}
printf '\e[1;33m%d\e[0m students got feedback.\n' ${#load[@]}
printf '\e[1;31m%d\e[0m students submitted nothing.\n' ${#empty[@]}

echo
if [ ${#empty[@]} -gt 0 ]; then
    declare -a name
    declare -a netid
    pat='([a-zA-Z ,]+)\(([a-z0-9]+)\)'
  printf "The following students have \e[1;36m%s\e[0m submission.\n" "NO"
  for i in "${empty[@]}"; do
    [[ "$i" =~ $pat ]] 
	name+=("${BASH_REMATCH[1]}")
	netid+=("${BASH_REMATCH[2]}")	
  done
fi


printf '\e[0;34m%s\e[0m\t\t\t\t\e[0;34m%s\e[0m\n' "Student Name" "NetID"
for ((i = 0; i < ${#name}; ++i)); do
   printf '%s\t\t%s\n' "${name[i]}" "${netid[i]}"
done
unset empty load total
